# Generated by Django 4.1.5 on 2023-04-07 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manual_chapter',
            fields=[
                ('Chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('Chapter_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manual_sub_chapter',
            fields=[
                ('Sub_chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('Sub_chapter_name', models.CharField(max_length=50)),
                ('Chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aquaponic_guide.manual_chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Manual_sub_chapter_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=500)),
                ('Sub_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aquaponic_guide.manual_sub_chapter')),
            ],
        ),
    ]
