# Generated by Django 4.1.5 on 2023-04-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aquaponic_guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual_sub_chapter_content',
            name='Content',
            field=models.TextField(max_length=500),
        ),
    ]
