# Generated by Django 4.1.5 on 2023-04-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aquaponic_guide', '0003_rename_chapter_name_manual_chapter_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manual_sub_chapter',
            old_name='Chapter',
            new_name='Chapter_id',
        ),
        migrations.RenameField(
            model_name='manual_sub_chapter',
            old_name='Sub_chapter_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='manual_sub_chapter_content',
            old_name='Sub_chapter',
            new_name='Sub_chapter_id',
        ),
    ]
