# Generated by Django 4.1.5 on 2023-04-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aquaponic_guide', '0004_rename_chapter_manual_sub_chapter_chapter_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manual_sub_chapter_content',
            old_name='Content',
            new_name='description',
        ),
    ]
