# Generated by Django 4.1.5 on 2023-04-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aquaponic_guide', '0005_rename_content_manual_sub_chapter_content_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manual_chapter',
            old_name='name',
            new_name='Chapter',
        ),
        migrations.RenameField(
            model_name='manual_sub_chapter',
            old_name='name',
            new_name='Sub_chapter',
        ),
        migrations.RenameField(
            model_name='manual_sub_chapter_content',
            old_name='description',
            new_name='Conter',
        ),
    ]
