# Generated by Django 4.1.5 on 2023-04-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aquaponic_guide', '0006_rename_name_manual_chapter_chapter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manual_sub_chapter_content',
            old_name='Conter',
            new_name='Content',
        ),
    ]
